# Generated by Django 2.2.6 on 2019-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thum',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
